### ISSUE TITLE
Cant install CadQuery

### ISSUE THREAD

**Issue by giannissc** [bernhard-42/vscode-cadquery-viewer#6]
This extension cannot install the cadquery dependency with any of the methods provided.

**Comment by bernhard-42** [comment]
Could you add some more details on what you do and what happens?
Which version of cq_vscode and ocp_tessellate are you using?

**Comment by bernhard-42** [comment]
There is an issue with cadquery installation using conda on Windows, however, with pip it worked for me on both Windows and MacOS (cq_vscode version 0.29.0)

**Comment by bernhard-42** [comment]
see https://github.com/bernhard-42/vscode-cadquery-viewer/issues/7

**Comment by giannissc** [comment]
I am running this on linux
This is the error I get with pip
```
Ignored the following versions that require a different python version: 0.7 Requires-Python ~=2.7, >=3.4

ERROR: Could not find a version that satisfies the requirement casadi (from cadquery) (from versions: none)

ERROR: No matching distribution found for casadi
```

**Comment by bernhard-42** [comment]
VS Code uses pip. are you able to install cadquery in your environment from the command line?
Does VS Code use the correct python as seen in the terminal output of VS Code?
Is `env -u CONDA_PREFIX_1` part of the command?
If you look into pypi.org, is casadi supported for your version of Python?

I know lot's of questions. But really all VS Code does is issue the pip command in a terminal ...

**Comment by giannissc** [comment]
I have actually fixed the issue through vscode. So originally I had a custom environement with all the dependecies installed but the extension would recognise. But it turned out it was just a setting for vscode.
This is the solution:
[Screencast from 2023-03-18 14-38-06.webm](https://user-images.githubusercontent.com/20277283/226112855-3d969976-dfde-4077-9d1e-d29eba65f957.webm)
